### ISSUE TITLE
Video call initiator is black screen (during direct video call)

### ISSUE THREAD

**Issue by Joshndroid** [SchildiChat/SchildiChat-android#173]
**Describe the bug**
Doing a direct video call one of the participants (usually the one initiating the video call is a black screen. The other person works just fine. It used to work perfectly but in the last few months it has become this way where one person is always black screen.

**To Reproduce**
Make a video call. The initiator of the call is usually black screen

**Expected behavior**
be able to see both participants

**Smartphone (please complete the following information):**
Samsung S21 Ultra & Pixel 7 Pro

**Additional context**
 - App version:1.5.8.sc62 [40100990] (f-39aff9f2)
 - Store: fdroid
 - Homeserver: self hosted instance, it was working for many months and now longer does. Self hosted instance is updated as per matrix-ansible version. Made some of the changed within the jitsi section for matrix with no change

**Upstream relevance**
 - Does this issue exist in Element Android? yes
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet) - https://github.com/vector-im/element-android/issues/7619

**Comment by Joshndroid** [comment]
It appears we might have some upstream movement on this finally with this being closed today https://github.com/vector-im/element-android/issues/7619

It appears this was the merge that closed the issue https://github.com/vector-im/element-android/pull/8383

Any possibility in merging from upstream with this and pushing out a new build? It's pretty significant if it fixes the blank video call issue

**Comment by SpiritCroc** [comment]
Planning to merge upstream once they tag the next release, like usually. Could probably be due soon-ish judging their release cycle?

**Comment by Joshndroid** [comment]
Hey mate, element-android just released their new version 1.6.. Super keen to get the video fixes merged, cheers

**Comment by rajil** [comment]
Since upstream bug is fixed, can you get this fixed.

**Comment by SpiritCroc** [comment]
1.6.0 has been merged (pushed to sc_beta branch). I'm not rushing a release for this one since upstream switched the crypto SDK, so we want to at least wait for them to roll-out 100% to production to be on the safe side regarding bugs from that change.

**Comment by rajil** [comment]
I have tested upstream 1.6 and it has worked fine. Is there a beta release apk available (gplay version) which I can use until you make a stable release?

**Comment by SpiritCroc** [comment]
Not yet, but it may appear maybe later this week in the beta-fdroid-repo linked at https://schildi.chat/android/ .

**Comment by Joshndroid** [comment]
Has this been pushed as yet? Tried video calls tonight and still broken for me

**Comment by SpiritCroc** [comment]
It's included in the latest beta. I'm waiting for upstream to push 1.6 to production before doing the same in case there are some rust crypto bugs that still need fixing.
